name: CI

on: [push]

jobs:
  ktlint:
    name: Run ktlint
    runs-on: macOS-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Run ktlint
      run: ./gradlew ktlint
