name: CI

on: [push]

jobs:
  ktlint:
    name: Run ktlint
    runs-on: macOS-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Run ktlint
      run: ./gradlew ktlint
